--INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('blabla',230000,'22/10/17',1);

SELECT AP.IDAPODERADO, AC.MONTORECAUDADO FROM ACTIVIDAD AC JOIN APODERADO AP ON AC.IDCURSOFK = AP.IDCURSOFK WHERE AP.IDCURSOFK = 1;

--SELECT MOD(SUM(AC.MONTORECAUDADO), COUNT(AP.IDAPODERADO)) FROM ACTIVIDAD AC JOIN APODERADO AP ON AC.IDCURSOFK = AP.IDCURSOFK WHERE IDCURSOFK = 1;

--RETORNA LA CANTIDAD DE APODERADOS EN ESE CURSO
SELECT COUNT(*) IDAPODERADO FROM APODERADO WHERE IDCURSOFK = 1;

--SELECT MOD(SUM(MONTORECAUDADO), (SELECT COUNT(IDAPODERADO) FROM APODERADO)) FROM ACTIVIDAD WHERE IDCURSOFK = 1;

--SELECT MOD(SUM(MONTORECAUDADO), 4) FROM ACTIVIDAD WHERE IDCURSOFK = 1;

--RETORNA EL MONTO TOTAL RECAUDADO DE UN CURSO
SELECT SUM(MONTORECAUDADO) FROM ACTIVIDAD WHERE IDCURSOFK = 1;

--RETORNA LA CANTIDAD DE APODERADOS DE UN CURSO
SELECT COUNT(IDAPODERADO) FROM APODERADO WHERE IDCURSOFK = 1;

--RETORNA LA CANTIDAD DE APODERADOS REGISTRADOS
SELECT COUNT(IDAPODERADO) FROM APODERADO;

-- POR AHORA ES EL QUE MAS SE ACERCA
SELECT (SUM(AC.MONTORECAUDADO) / COUNT(AP.IDAPODERADO)) AS PRORRATEO FROM ACTIVIDAD AC JOIN APODERADO AP ON AC.IDCURSOFK = AP.IDCURSOFK WHERE AC.IDCURSOFK = 1;

--SIGUE DANDO 195000 COMO SI LA CANTIDAD DE APODERADOS SIEMPRE FUERA 4 EN VEZ DE 6
SELECT 
SUM(AC.MONTORECAUDADO) / COUNT(AP.IDAPODERADO) FROM APODERADO AP JOIN ACTIVIDAD AC ON AP.IDCURSOFK = AC.IDCURSOFK WHERE AP.IDCURSOFK = 1;

--LO MISMO DE ARRIBA
SELECT SUM(AC.MONTORECAUDADO) / COUNT(*) FROM APODERADO AP, ACTIVIDAD AC WHERE AP.IDCURSOFK = 1 AND AC.IDCURSOFK = 1;
