SELECT * FROM USUARIO WHERE CORREO = 'niim12@ontour.cl';

SELECT COUNT(*) FROM DEPOSITO WHERE IDAPODERADOFK = 1;

INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Rafael Eyzaguirre','Calle Paula Montal #666','contacto@cre.cl','+56966666666');

INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDAPODERADOFK) VALUES (20000,'01/02/17','Primer deposito','URLRANDOM',42);

INSERT INTO DEPOSITO (IDDEPOSITO,MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDAPODERADOFK) VALUES (6,24145,'08-08-17','turpis. Aliquam','www.photobucket.com/user/ontour/gallery/18038',1); 
INSERT INTO DEPOSITO (IDDEPOSITO,MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDAPODERADOFK) VALUES (6,24145,'08-08-17','turpis. Aliquam','www.photobucket.com/user/ontour/gallery/18038',1);   
INSERT INTO DEPOSITO (IDDEPOSITO,MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDAPODERADOFK,CORREOFK) VALUES (7,30000,'08-08-17','Primer deposito Alonso','etc',42,'alon.berrios@alumnos.duoc.cl');
INSERT INTO DEPOSITO (IDDEPOSITO,MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDAPODERADOFK,CORREOFK) VALUES (9,20000,'09-08-17','Segundo deposito Alonso','etc',42,'alon.berrios@alumnos.duoc.cl');

SELECT IDDEPOSITO AS CODIGO, CONCAT('$',MONTO) AS MONTO, TO_CHAR(FECHA, 'dd/mm/yy') AS FECHA, COMENTARIO FROM DEPOSITO WHERE CORREOFK = 'alon.berrios@gmail.com';

-- WEB SERVICE DE SEGURO
-- CONSULTA PARA LA CANTIDAD DE APODERADOS DE UN CURSO
SELECT COUNT(*) FROM APODERADO WHERE IDCURSOFK = 1;
-- CONSULTA PARA LA CANTIDAD DE DIAS
SELECT PT.DIAS 
FROM PAQUETETURISTICO PT JOIN CONTRATO CO ON PT.IDPAQUETETURISTICO = CO.IDPAQUETETURISTICOFK
WHERE CO.IDCURSOFK = 1;
