
--////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

--COLEGIO
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','544-1131 Ut, Av.','contacto@alcantara.cl','038-229-5281');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Instituto Nacional','P.O. Box 444, 374 Pulvinar Road','contacto@in.cl','086-932-1043');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','P.O. Box 124, 2990 In Street','contacto@ccordillera.cl','000-056-4088');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('ICS','Ap #377-2198 Nulla Rd.','contacto@ics.cl','077-686-5016');

/* Sobras
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','4225 Vivamus Avenue','contacto@in.cl','037-051-3549');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #583-3003 Fames Ave','contacto@alcantara.cl','057-827-1818');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','484-8920 Nibh. Road','contacto@in.cl','068-361-3227');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 667, 5195 Cursus. St.','contacto@in.cl','095-035-0229');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 953, 4274 Morbi Road','contacto@ics.cl','047-410-4274');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 285, 1314 Libero Street','contacto@in.cl','082-581-2132');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 625, 4638 Fringilla St.','contacto@ccordillera.cl','057-457-1677');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('ICS','P.O. Box 638, 4804 Enim. Av.','contacto@in.cl','082-693-3839');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','5346 Ligula. St.','contacto@alcantara.cl','003-419-9998');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','808-3332 Elit Av.','contacto@ccordillera.cl','044-401-9229');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 421, 271 Vitae, Av.','contacto@alcantara.cl','000-908-7217');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','7361 Amet Road','contacto@alcantara.cl','083-690-3872');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','342-4601 Ac Street','contacto@ics.cl','077-407-9983');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('ICS','P.O. Box 649, 7793 Eu Av.','contacto@alcantara.cl','005-212-6378');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #843-9634 Morbi Av.','contacto@ics.cl','035-895-6809');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','P.O. Box 355, 5236 Eu Ave','contacto@ics.cl','080-975-7992');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #150-321 Dictum Avenue','contacto@alcantara.cl','069-214-2173');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','9785 Commodo Ave','contacto@alcantara.cl','057-820-2873');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','9697 Feugiat. Rd.','contacto@in.cl','072-052-9409');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','5047 Id, St.','contacto@ccordillera.cl','089-718-3372');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 383, 3699 Integer Avenue','contacto@alcantara.cl','062-742-4181');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','9966 Eu St.','contacto@alcantara.cl','039-232-2685');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','990-5002 Pede, Road','contacto@ics.cl','016-236-4294');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #700-4726 Nascetur Ave','contacto@in.cl','099-886-3941');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','1851 Eu Ave','contacto@in.cl','067-834-4097');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 278, 3303 Enim Street','contacto@ics.cl','098-003-2825');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('ICS','5878 Senectus Av.','contacto@in.cl','017-362-5185');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','4552 At, Av.','contacto@ccordillera.cl','090-530-1331');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','3755 Aliquam Street','contacto@alcantara.cl','011-159-5319');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','Ap #188-949 Augue Ave','contacto@in.cl','069-200-3609');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','107-2100 A Avenue','contacto@alcantara.cl','026-194-3936');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #510-1915 Molestie Street','contacto@in.cl','047-059-6995');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Instituto Nacional','Ap #556-7343 Suspendisse St.','contacto@in.cl','007-372-5946');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','9202 Aliquet Av.','contacto@in.cl','044-735-4298');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','2552 Ligula St.','contacto@alcantara.cl','009-659-1193');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #272-346 Sem, St.','contacto@ccordillera.cl','064-860-9594');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','2749 Sit Rd.','contacto@ics.cl','081-888-1642');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','8523 Aliquet Rd.','contacto@in.cl','024-295-9343');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','8055 Pellentesque Rd.','contacto@ics.cl','086-084-8787');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','2099 Cursus Ave','contacto@in.cl','052-817-8248');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #359-1107 Luctus St.','contacto@ics.cl','083-704-4629');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 423, 7239 Scelerisque Avenue','contacto@in.cl','018-233-3763');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #299-5380 Dui. Street','contacto@alcantara.cl','008-698-4895');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 207, 2656 Sit St.','contacto@alcantara.cl','001-747-4403');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','377-5631 Montes, St.','contacto@ics.cl','087-700-8968');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','P.O. Box 560, 5893 Suspendisse Rd.','contacto@ics.cl','074-662-6265');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','200-8677 Hendrerit Ave','contacto@alcantara.cl','083-731-1116');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','9573 Sem St.','contacto@in.cl','014-841-7107');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','Ap #703-5867 Nullam St.','contacto@ccordillera.cl','017-410-3604');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','640-2522 Habitant Road','contacto@ccordillera.cl','032-686-2223');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 410, 8267 Ut St.','contacto@ics.cl','001-008-5128');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #319-9793 Quisque Rd.','contacto@alcantara.cl','087-391-1196');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #712-5764 Arcu Av.','contacto@ccordillera.cl','064-091-8484');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','177-2089 Odio Street','contacto@ccordillera.cl','083-510-8589');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','9060 Donec Street','contacto@ccordillera.cl','037-464-8879');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','2286 Diam. St.','contacto@alcantara.cl','046-289-1356');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','646-3214 Montes, Street','contacto@ccordillera.cl','058-880-9093');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','981-241 Phasellus Avenue','contacto@ccordillera.cl','092-808-1736');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #843-3905 Sit St.','contacto@ics.cl','090-572-4031');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','P.O. Box 314, 6213 Dis St.','contacto@in.cl','094-002-1533');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('ICS','838-676 Sollicitudin Av.','contacto@ics.cl','075-297-0430');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','P.O. Box 692, 1383 Consequat Avenue','contacto@ccordillera.cl','080-462-8643');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','8789 Mauris Rd.','contacto@ccordillera.cl','007-175-7332');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','574-9835 Malesuada Avenue','contacto@alcantara.cl','068-394-3083');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','767-655 Elit Rd.','contacto@ics.cl','073-479-1794');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','883-3736 Facilisis Avenue','contacto@ccordillera.cl','074-053-2574');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','P.O. Box 524, 8276 Risus. Avenue','contacto@ics.cl','044-582-6681');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','P.O. Box 945, 6517 Sed Street','contacto@ics.cl','014-801-1520');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','P.O. Box 634, 4523 Mollis Road','contacto@ics.cl','084-933-0780');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Instituto Nacional','840-7746 Ut Street','contacto@ccordillera.cl','004-515-4918');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','2224 Ligula Street','contacto@alcantara.cl','081-030-5761');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','448-7944 Praesent Rd.','contacto@in.cl','004-831-5923');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('ICS','P.O. Box 426, 7535 Sed Avenue','contacto@alcantara.cl','075-480-9901');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','4198 Dolor Rd.','contacto@ccordillera.cl','061-308-5939');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','4688 Mauris Avenue','contacto@alcantara.cl','029-291-0209');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','371-9573 Mi St.','contacto@alcantara.cl','045-675-0248');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('ICS','453-8312 Augue Rd.','contacto@alcantara.cl','011-524-6444');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Instituto Nacional','5199 Enim Av.','contacto@ics.cl','079-247-1917');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','329-9466 Libero Rd.','contacto@in.cl','025-363-4168');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #701-9960 Id, Rd.','contacto@in.cl','093-150-4957');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','Ap #637-9374 Tincidunt Street','contacto@ccordillera.cl','000-298-4849');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','P.O. Box 340, 1675 Libero. Rd.','contacto@alcantara.cl','066-601-9067');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','P.O. Box 354, 5823 Mauris. St.','contacto@in.cl','028-335-2212');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','2555 Risus Road','contacto@alcantara.cl','015-420-3418');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','686-3887 Varius Avenue','contacto@in.cl','061-814-6880');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','6964 Est. Ave','contacto@in.cl','075-812-4714');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','930-6913 Enim. Rd.','contacto@in.cl','075-492-0829');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Alicante del Sol','808-9541 Etiam Rd.','contacto@in.cl','058-844-7589');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('','764-230 Magna Avenue','contacto@alcantara.cl','039-223-0468');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','Ap #139-3515 Mauris Avenue','contacto@ics.cl','008-141-4392');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Instituto Nacional','8002 Lorem, Rd.','contacto@ccordillera.cl','031-704-8611');
INSERT INTO COLEGIO (NOMBRECOLEGIO,DIRECCION,CORREO,TELEFONO) VALUES ('Cordillera','945-7292 Vitae Rd.','contacto@alcantara.cl','049-063-3198');
*/

--////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

--CURSO
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','E',6,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','F',6,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','D',6,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','A',6,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','H',6,4);

/* Agregar solo en caso de querer poblar con mas datos
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',14,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','B',20,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','H',15,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','B',11,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',19,4);
*/

/* Sobras
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',20,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',21,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','H',29,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','C',25,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','H',16,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','E',22,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','E',22,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','A',20,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',25,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','A',27,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','A',23,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','D',35,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',38,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','E',20,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',37,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','E',18,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','E',29,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','E',21,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','B',21,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','E',23,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','F',20,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','C',16,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',38,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','F',33,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','F',24,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',40,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',35,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','A',24,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','C',18,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',26,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','D',23,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','E',21,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','H',38,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','H',19,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','D',40,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',27,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','H',35,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','B',23,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','B',23,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','D',29,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','H',21,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','D',19,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',15,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',34,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','A',24,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','A',27,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','F',33,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','B',23,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','F',25,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','B',35,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','E',16,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','A',21,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',22,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',39,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',40,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','B',35,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','C',28,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','F',36,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','F',20,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','D',30,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',30,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','F',26,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','H',16,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','B',27,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','A',33,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','A',29,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','D',23,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','A',38,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',21,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','C',33,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','E',38,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','D',30,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',30,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','E',29,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','H',15,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',24,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','F',15,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','C',34,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','H',17,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','B',27,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','C',23,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','E',39,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','F',24,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','A',37,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','H',37,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','H',35,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','A',29,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','A',18,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',23,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','A',19,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','G',22,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','C',39,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','D',15,2);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','F',24,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','B',39,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','C',16,1);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','A',36,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('4to Medio','H',20,4);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','B',21,3);
INSERT INTO CURSO (GRADOCURSO,LETRACURSO,CANTIDADALUMNOS,IDCOLEGIOFK) VALUES ('3ro Medio','G',28,4);
*/

--////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

--TIPOUSUARIO
INSERT INTO TIPOUSUARIO (ROL) VALUES ('Apoderado');
INSERT INTO TIPOUSUARIO (ROL) VALUES ('Representante');
INSERT INTO TIPOUSUARIO (ROL) VALUES ('Administrador');
INSERT INTO TIPOUSUARIO (ROL) VALUES ('Ejecutivo');
INSERT INTO TIPOUSUARIO (ROL) VALUES ('Gerente');

--////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

--USUARIO

--Usuarios REPRESENTANTES
--Curso 1
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('rep1@ontour.cl','9700',2);
--Curso 2
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('rep2@ontour.cl','2006',2);
--Curso 3
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('rep3@ontour.cl','5647',2);
--Curso 4
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('rep4@ontour.cl','3709',2);
--Curso 5
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('rep5@ontour.cl','2343',2);

/* Agregar solo en caso de querer poblar con mas datos
--Curso 6
INSERT INTO APODERADO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apoderado6@ontour.cl','1243',2);
--Curso 7
INSERT INTO APODERADO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apoderado7@ontour.cl','2338',2);
--Curso 8
INSERT INTO APODERADO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apoderado8@ontour.cl','4656',2);
--Curso 9
INSERT INTO APODERADO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apoderado9@ontour.cl','6251',2);
--Curso 10
INSERT INTO APODERADO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apoderado10@ontour.cl','5256',2);
*/

--Usuarios APODERADOS
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo1@ontour.cl','7301',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo2@ontour.cl','3973',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo3@ontour.cl','7407',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo4@ontour.cl','6109',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo5@ontour.cl','2883',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo6@ontour.cl','3389',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo7@ontour.cl','1972',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo8@ontour.cl','6980',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo9@ontour.cl','7367',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo10@ontour.cl','8618',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo11@ontour.cl','9013',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo12@ontour.cl','5753',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo13@ontour.cl','7432',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo14@ontour.cl','2274',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo15@ontour.cl','7992',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo16@ontour.cl','6984',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo17@ontour.cl','6750',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo18@ontour.cl','4605',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo19@ontour.cl','9416',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo20@ontour.cl','1521',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo21@ontour.cl','1996',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo22@ontour.cl','1445',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo23@ontour.cl','3028',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo24@ontour.cl','8246',1);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('apo25@ontour.cl','6369',1);
--Datos de prueba personalizado
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('alon.berrios@gmail.com','8000',1);

--Usuarios EJECUTIVOS
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('exe1@ontour.cl','5792',4);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('exe2@ontour.cl','7800',4);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('exe3@ontour.cl','0994',4);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('exe4@ontour.cl','8000',4);
INSERT INTO USUARIO (CORREO,CLAVE,IDTIPOUSUARIOFK) VALUES ('exe5@ontour.cl','9000',4);

--150 registros | solo datos de apoderado: direccion, telefono, sexo, fecha de nacimiento
/* Toyo
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('7884 Ornare, Av.','+569-57081467','F','15-11-63');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('279-5978 Dolor. Ave','+569-96777263','F','10-05-52');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #517-233 At, St.','+569-48421192','M','13-03-46');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('5717 Vitae Street','+569-61973609','M','10-03-51');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('289-762 Suscipit Rd.','+569-57322939','M','29-12-50');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('3659 Duis Avenue','+569-34962824','F','10-08-59');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 324, 1934 Morbi Rd.','+569-44582267','F','29-03-74');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('171-9395 Donec Street','+569-28852181','F','02-11-71');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 803, 4831 Nascetur St.','+569-54277245','M','29-07-47');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 418, 4078 Vulputate Av.','+569-63785134','M','23-03-75');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('672-2753 Lobortis Rd.','+569-60132674','M','02-09-65');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 267, 9713 Tempor St.','+569-25486033','M','24-01-83');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 783, 1728 Condimentum Street','+569-37649556','F','05-10-52');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #900-3431 A, Av.','+569-52492047','F','28-08-45');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #131-3520 Lorem St.','+569-62826325','M','29-03-55');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 241, 3960 Tempor Rd.','+569-51975153','M','17-05-46');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('1486 Sed Road','+569-87932592','M','22-12-92');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('8721 Ipsum Avenue','+569-37625053','M','06-06-76');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 552, 8573 Maecenas St.','+569-84557166','M','14-07-54');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 254, 1601 Laoreet Av.','+569-81036664','F','19-01-81');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('3625 Etiam St.','+569-65985042','M','06-11-56');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #435-8825 Lectus. Ave','+569-62671002','M','05-09-94');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #405-3515 Sit Avenue','+569-90953351','M','20-10-40');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('1324 Ullamcorper Av.','+569-41134208','F','12-09-54');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('588-8736 Vel, Rd.','+569-72291306','F','27-12-78');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('424-7397 Dignissim Rd.','+569-65806177','M','17-09-82');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 832, 7918 Enim Rd.','+569-35771079','M','16-04-84');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('1297 Sociis Avenue','+569-93581902','M','25-05-42');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 682, 8149 Orci. Street','+569-71746739','M','24-10-68');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #583-4062 Eget Av.','+569-43696559','M','20-10-40');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('145-2312 In Rd.','+569-32957588','F','10-06-90');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 456, 9464 Curabitur St.','+569-96794270','M','28-08-92');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #114-9048 Nunc Road','+569-25204890','M','20-01-82');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('587-1338 Consequat St.','+569-46875728','M','12-07-59');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #602-1431 Mauris Rd.','+569-38335439','M','06-06-69');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 981, 6168 Nibh Av.','+569-35398832','F','24-07-75');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('7467 Vulputate, Av.','+569-97438936','M','23-07-91');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('5967 Mauris Road','+569-24791286','M','10-04-73');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('1726 Mauris, Av.','+569-70325907','M','22-01-45');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('6124 Luctus St.','+569-51984268','M','08-01-94');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('991-8698 Dui. St.','+569-83603723','M','16-09-51');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #224-7064 Praesent Rd.','+569-37871177','F','19-06-56');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 187, 2981 Et, Av.','+569-87795756','F','07-05-53');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #672-202 Ut Road','+569-37421577','M','05-02-42');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #815-7059 Mauris St.','+569-65089730','F','30-01-87');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #402-7561 Nisi Rd.','+569-39457150','M','25-05-61');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #865-8274 Ipsum St.','+569-94395003','F','09-04-66');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 105, 6940 Sed Rd.','+569-65215609','F','04-12-80');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 470, 9778 Mattis St.','+569-61149086','M','19-07-47');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 349, 2946 Fermentum St.','+569-48971325','F','25-01-43');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('150-1786 A St.','+569-25888195','F','03-09-40');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('4253 Ornare. St.','+569-71716035','M','26-01-52');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('2497 Cras Road','+569-48215782','M','18-10-68');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('790-6762 Donec Street','+569-49821065','F','17-08-57');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 859, 1663 Aliquet Road','+569-10022331','F','28-12-45');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #778-6508 Ultrices Rd.','+569-81577119','F','07-06-43');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('2663 Faucibus Street','+569-53885448','M','03-08-65');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('325-2388 Ac Avenue','+569-10708167','M','22-09-53');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 713, 8738 Luctus Avenue','+569-81808061','M','09-05-87');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('305-1222 Vel St.','+569-23359067','M','23-01-74');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('792-6518 Diam Av.','+569-18223532','M','22-10-73');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #205-8514 Et, Rd.','+569-15664319','M','07-05-47');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #163-3406 Nec Av.','+569-62459872','M','08-04-84');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 165, 8861 Rhoncus. Street','+569-75222708','M','28-04-42');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('6484 Interdum. Rd.','+569-17606951','M','07-10-57');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('628-3566 Tellus Street','+569-91012789','F','06-12-70');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('974-5730 Vestibulum Avenue','+569-53421402','M','03-02-76');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #513-3476 Ut Road','+569-85349368','F','31-10-92');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #609-5212 In, St.','+569-57092031','M','06-09-58');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 875, 8851 Nulla St.','+569-34103258','M','13-01-44');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('3742 Sit Ave','+569-19094695','F','23-02-53');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('750-9926 Vulputate Av.','+569-40137224','F','22-08-91');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 642, 9337 Sit Rd.','+569-91152001','F','05-01-58');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('633-8277 Eu Rd.','+569-63261363','F','26-01-71');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('395-2117 Ultrices Avenue','+569-77693799','F','12-08-87');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 433, 3869 Elementum, Street','+569-85491900','F','29-01-86');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #302-3042 Massa. Avenue','+569-21986890','F','24-06-75');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('185-7813 Mauris Road','+569-32512014','M','29-07-75');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('2690 Laoreet St.','+569-40856769','M','16-02-82');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('6878 Ullamcorper. St.','+569-62754201','M','07-07-56');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('2439 Vel Rd.','+569-47728162','M','15-10-47');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #979-2259 Mauris, Road','+569-75375794','F','29-09-73');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #498-6642 Eu St.','+569-55342461','F','19-09-80');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #464-8261 Sed, Av.','+569-15577306','M','15-11-67');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('363-8306 Velit. Rd.','+569-42013066','F','28-05-61');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('480-6342 Dapibus Avenue','+569-23795644','F','26-03-62');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('8058 Fames Avenue','+569-46908687','M','16-11-71');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #922-7292 Sed Road','+569-87697936','M','11-08-73');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('4279 Non, Rd.','+569-58448888','F','19-05-51');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 386, 4447 Proin Av.','+569-43212355','M','03-11-72');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 233, 9719 At, St.','+569-86398729','M','28-05-75');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #195-5124 Malesuada Avenue','+569-34159278','F','09-11-87');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('6462 Erat, Rd.','+569-94337138','M','02-08-52');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('535-2737 Augue, St.','+569-40345004','F','24-10-71');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #108-8271 Nisl St.','+569-22635491','M','26-03-49');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('992-560 Ipsum. Road','+569-66126501','F','25-04-83');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('7222 Nunc Street','+569-66523474','F','31-01-79');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('P.O. Box 215, 5546 Varius Avenue','+569-27111184','M','01-10-76');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('Ap #374-5262 Tristique Street','+569-15998029','F','06-08-71');
INSERT INTO APODERADO (DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO) VALUES ('482-9248 Augue Avenue','+569-84715329','M','15-12-44');
*/

--////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

--APODERADO

--Correspondiente a los usuarios representantes
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('12083446-0','Gary','Duffy','Pierce','171-9395 Donec Street','+569-28852181','M','02-11-71',0,1,1,'rep1@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('48502049-7','Sandra','Molina','Preston','P.O. Box 803, 4831 Nascetur St.','+569-54277245','F','29-07-47',0,1,2,'rep2@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('25547864-8','Maya','Vincent','Shannon','P.O. Box 418, 4078 Vulputate Av.','+569-63785134','F','23-03-75',0,2,3,'rep3@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('41259371-5','Thane','Frazier','Cline','8721 Ipsum Avenue','+569-37625053','F','06-06-76',0,3,4,'rep4@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('5068235-8','Brock','Hubbard','Morton','3625 Etiam St.','+569-65985042','M','06-11-56',0,4,5,'rep5@ontour.cl');

--Colegio 1, curso 1
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('16566806-5','Fuller','Le','Powers','Ap #672-202 Ut Road','+569-37421577','M','05-02-42',0,1,1,'apo1@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('46321087-K','Judith','Booth','Hatfield','2497 Cras Road','+569-48215782','F','18-10-68',0,1,1,'apo2@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('16517936-6','Quamar','Ray','Cortez','6124 Luctus St.','+569-51984268','M','08-01-94',0,1,1,'apo3@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('27874120-6','Aretha','Murray','Solomon','305-1222 Vel St.','+569-23359067','F','23-01-74',0,1,1,'apo4@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('28490955-0','Hyatt','Farley','Frye','792-6518 Diam Av.','+569-18223532','M','22-10-73',0,1,1,'apo5@ontour.cl');

--Colegio 1, curso 2
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('38042390-1','Ezra','Levy','Baldwin','Ap #205-8514 Et, Rd.','+569-15664319','M','07-05-47',0,1,2,'apo6@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('7142838-9','Shad','Vance','Schroeder','Ap #163-3406 Nec Av.','+569-62459872','M','08-04-84',0,1,2,'apo7@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('35065248-5','Gregory','Houston','Underwood','628-3566 Tellus Street','+569-91012789','M','06-12-70',0,1,2,'apo8@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('40700237-7','Mohammad','Walters','Blanchard','974-5730 Vestibulum Avenue','+569-53421402','M','03-02-76',0,1,2,'apo9@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('6908244-0','Lacey','Tate','Obrien','Ap #513-3476 Ut Road','+569-85349368','F','31-10-92',0,1,2,'apo10@ontour.cl');

--Colegio 2, curso 3
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('36195212-K','Keane','Ayala','Baker','P.O. Box 233, 9719 At, St.','+569-86398729','M','28-05-75',0,2,3,'apo11@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('18128085-9','Brennan','Workman','Chandler','Ap #195-5124 Malesuada Avenue','+569-34159278','M','09-11-87',0,2,3,'apo12@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('15339527-6','Xenos','Williams','Hawkins','6462 Erat, Rd.','+569-94337138','M','02-08-52',0,2,3,'apo13@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('18572945-1','Devin','Rowe','Daniel','535-2737 Augue, St.','+569-40345004','M','24-10-71',0,2,3,'apo14@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('27079898-5','Zane','Camacho','Hernandez','Ap #108-8271 Nisl St.','+569-22635491','M','26-03-49',0,2,3,'apo15@ontour.cl');

--Colegio 3, curso 4
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('47394379-4','Anthony','Dotson','Chandler','992-560 Ipsum. Road','+569-66126501','M','25-04-83',0,3,4,'apo16@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('40751182-4','Isaiah','Mcdaniel','Thomas','7222 Nunc Street','+569-66523474','M','31-01-79',0,3,4,'apo17@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('24885360-3','Anastasia','Cline','Boyer','P.O. Box 215, 5546 Varius Avenue','+569-27111184','F','01-10-76',0,3,4,'apo18@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('18378192-8','Maia','Craig','Anthony','Ap #374-5262 Tristique Street','+569-15998029','F','06-08-71',0,3,4,'apo19@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('12863251-4','Sacha','Gilliam','Hoover','482-9248 Augue Avenue','+569-84715329','F','15-12-44',0,3,4,'apo20@ontour.cl');

--Colegio 4, curso 5
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('43603928-K','Lionel','Bradley','Lucas','P.O. Box 803, 4831 Nascetur St.','+569-54277245','M','29-07-47',0,4,5,'apo21@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('50750572-4','Claire','Kramer','Burton','7884 Ornare, Av.','+569-57081467','F','15-11-63',0,4,5,'apo22@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('28882900-4','Bree','Frazier','Ingram','279-5978 Dolor. Ave','+569-96777263','F','10-05-52',0,4,5,'apo23@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('24942514-1','Gavin','Roberts','Morales','5717 Vitae Street','+569-61973609','M','10-03-51',0,4,5,'apo24@ontour.cl');
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('44541583-9','Britanni','Pollard','Reyes','3659 Duis Avenue','+569-34962824','F','10-08-59',0,4,5,'apo25@ontour.cl');

--Datos de prueba personalizado
INSERT INTO APODERADO (RUT,NOMBRE,APELLIDOP,APELLIDOM,DIRECCION,TELEFONO,SEXO,FECHANACIMIENTO,MONTOPAGAR,IDCOLEGIOFK,IDCURSOFK,CORREOFK) VALUES ('18954313-1','Alonso','Berrios','Montecinos','Los Boldos #37418','+569-67572428','M','15-11-94',0,4,5,'alon.berrios@gmail.com');

--////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

--EJECUTIVO

INSERT INTO EJECUTIVO (RUT,NOMBRE,APELLIDOP,APELLIDOM,CORREOFK,IDCURSOFK) VALUES ('30597650-4','Jace','Beleren','Beleren','exe1@ontour.cl',1);
INSERT INTO EJECUTIVO (RUT,NOMBRE,APELLIDOP,APELLIDOM,CORREOFK,IDCURSOFK) VALUES ('22533427-7','Ajani','Goldmane','Goldmane','exe2@ontour.cl',2);
INSERT INTO EJECUTIVO (RUT,NOMBRE,APELLIDOP,APELLIDOM,CORREOFK,IDCURSOFK) VALUES ('20241823-6','Narset','Jeskai','Jeskai','exe3@ontour.cl',3);
INSERT INTO EJECUTIVO (RUT,NOMBRE,APELLIDOP,APELLIDOM,CORREOFK,IDCURSOFK) VALUES ('10000000-1','Arlinn','Kord','Kord','exe4@ontour.cl',4);
INSERT INTO EJECUTIVO (RUT,NOMBRE,APELLIDOP,APELLIDOM,CORREOFK,IDCURSOFK) VALUES ('1000000-1','Sorin','Markov','Markov','exe5@ontour.cl',5);

--////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

--DEPOSITO

INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,NOMBREIMAGEN,CORREOFK) VALUES (23444,'10-03-18','ipsum.',null,'apo1@ontour.cl');
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,NOMBREIMAGEN,CORREOFK) VALUES (39169,'25-07-18','magna. Ut tincidunt',null,'apo2@ontour.cl');
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,NOMBREIMAGEN,CORREOFK) VALUES (16049,'10-08-18','Nunc mauris',null,'apo3@ontour.cl');
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,NOMBREIMAGEN,CORREOFK) VALUES (11563,'18-06-17','elit, a',null,'apo4@ontour.cl');
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,NOMBREIMAGEN,CORREOFK) VALUES (18038,'08-08-17','turpis. Aliquam',null,'apo5@ontour.cl');

--Datos de prueba personalizados
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,NOMBREIMAGEN,CORREOFK) VALUES (20000,'08-08-17','Primer deposito Alonso','31-080817','alon.berrios@gmail.com');
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,NOMBREIMAGEN,CORREOFK) VALUES (30000,'09-08-17','Segundo deposito Alonso','31-090817','alon.berrios@gmail.com');

/* Sobras
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (29915,'29-01-17','non dui nec','www.photobucket.com/user/ontour/gallery/29915',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (21408,'13-09-18','eu nulla at','www.photobucket.com/user/ontour/gallery/21408',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (10448,'28-02-18','iaculis enim, sit amet ornare','www.photobucket.com/user/ontour/gallery/10448',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (23917,'19-01-18','diam lorem, auctor','www.photobucket.com/user/ontour/gallery/23917',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (8318,'28-04-18','vitae nibh. Donec est','www.photobucket.com/user/ontour/gallery/8318',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (15436,'03-11-16','quis,','www.photobucket.com/user/ontour/gallery/15436',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (16003,'30-10-17','consectetuer rhoncus. Nullam velit dui,','www.photobucket.com/user/ontour/gallery/16003',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (8978,'25-07-18','primis in faucibus orci','www.photobucket.com/user/ontour/gallery/8978',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (38376,'06-02-18','eu eros. Nam consequat','www.photobucket.com/user/ontour/gallery/38376',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (38074,'20-04-17','Nullam vitae diam.','www.photobucket.com/user/ontour/gallery/38074',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (38229,'06-02-18','cursus. Nunc mauris','www.photobucket.com/user/ontour/gallery/38229',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (44271,'10-12-16','vehicula et, rutrum','www.photobucket.com/user/ontour/gallery/44271',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (32856,'26-07-18','tellus lorem','www.photobucket.com/user/ontour/gallery/32856',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (12732,'31-05-17','commodo auctor velit.','www.photobucket.com/user/ontour/gallery/12732',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (48241,'21-04-18','eros. Nam','www.photobucket.com/user/ontour/gallery/48241',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (16629,'01-07-17','magnis dis parturient montes, nascetur','www.photobucket.com/user/ontour/gallery/16629',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (37075,'30-10-16','dictum eu, eleifend nec,','www.photobucket.com/user/ontour/gallery/37075',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (24831,'25-09-17','a, dui. Cras','www.photobucket.com/user/ontour/gallery/24831',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (44232,'30-01-18','nostra,','www.photobucket.com/user/ontour/gallery/44232',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (32487,'08-09-18','massa. Quisque porttitor','www.photobucket.com/user/ontour/gallery/32487',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (12729,'15-08-17','pellentesque massa','www.photobucket.com/user/ontour/gallery/12729',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (6306,'27-01-18','justo. Praesent luctus. Curabitur','www.photobucket.com/user/ontour/gallery/6306',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (36732,'21-09-18','dolor. Nulla semper','www.photobucket.com/user/ontour/gallery/36732',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (22522,'06-10-16','nec luctus','www.photobucket.com/user/ontour/gallery/22522',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (49314,'04-10-17','non','www.photobucket.com/user/ontour/gallery/49314',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (26032,'10-04-17','vulputate mauris','www.photobucket.com/user/ontour/gallery/26032',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (39448,'27-08-18','Duis dignissim','www.photobucket.com/user/ontour/gallery/39448',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (22322,'15-05-17','Integer','www.photobucket.com/user/ontour/gallery/22322',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (11043,'30-09-17','turpis. In','www.photobucket.com/user/ontour/gallery/11043',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (12587,'26-11-17','arcu. Sed eu nibh vulputate','www.photobucket.com/user/ontour/gallery/12587',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (38292,'08-07-17','sit amet,','www.photobucket.com/user/ontour/gallery/38292',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (43571,'13-04-18','Maecenas','www.photobucket.com/user/ontour/gallery/43571',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (40524,'22-06-17','egestas a, dui. Cras pellentesque.','www.photobucket.com/user/ontour/gallery/40524',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (24184,'05-06-18','dui.','www.photobucket.com/user/ontour/gallery/24184',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (29776,'03-06-18','Fusce dolor quam,','www.photobucket.com/user/ontour/gallery/29776',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (24409,'02-09-18','sapien molestie orci','www.photobucket.com/user/ontour/gallery/24409',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (33430,'17-10-17','ut, molestie in, tempus','www.photobucket.com/user/ontour/gallery/33430',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (38498,'10-04-18','quis, pede. Suspendisse','www.photobucket.com/user/ontour/gallery/38498',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (7187,'09-05-17','ac mattis','www.photobucket.com/user/ontour/gallery/7187',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (16275,'22-04-18','nec tempus','www.photobucket.com/user/ontour/gallery/16275',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (37963,'16-01-18','metus. In nec','www.photobucket.com/user/ontour/gallery/37963',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (12838,'15-02-18','ut,','www.photobucket.com/user/ontour/gallery/12838',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (20759,'27-10-16','eget tincidunt dui augue eu','www.photobucket.com/user/ontour/gallery/20759',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (33921,'18-04-18','iaculis, lacus pede','www.photobucket.com/user/ontour/gallery/33921',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (19887,'14-04-17','arcu.','www.photobucket.com/user/ontour/gallery/19887',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (21611,'28-06-17','Quisque fringilla euismod','www.photobucket.com/user/ontour/gallery/21611',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (25546,'11-12-16','dictum. Proin eget odio. Aliquam','www.photobucket.com/user/ontour/gallery/25546',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (37402,'23-01-17','Nulla facilisi. Sed neque.','www.photobucket.com/user/ontour/gallery/37402',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (19665,'16-02-17','elit sed consequat','www.photobucket.com/user/ontour/gallery/19665',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (32855,'01-08-18','egestas','www.photobucket.com/user/ontour/gallery/32855',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (6324,'14-09-18','et ultrices posuere','www.photobucket.com/user/ontour/gallery/6324',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (11652,'17-10-17','ante dictum','www.photobucket.com/user/ontour/gallery/11652',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (14167,'26-05-18','euismod urna. Nullam lobortis quam','www.photobucket.com/user/ontour/gallery/14167',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (8066,'05-12-17','molestie arcu. Sed eu nibh','www.photobucket.com/user/ontour/gallery/8066',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (25257,'14-08-17','aliquet, sem ut cursus luctus,','www.photobucket.com/user/ontour/gallery/25257',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (24785,'25-11-16','risus. Quisque libero lacus,','www.photobucket.com/user/ontour/gallery/24785',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (12574,'24-02-18','Cras pellentesque. Sed dictum. Proin','www.photobucket.com/user/ontour/gallery/12574',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (44948,'19-07-18','faucibus orci luctus','www.photobucket.com/user/ontour/gallery/44948',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (39486,'29-09-17','Sed eu','www.photobucket.com/user/ontour/gallery/39486',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (38723,'28-01-17','pharetra, felis','www.photobucket.com/user/ontour/gallery/38723',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (46776,'26-01-18','sit amet lorem semper auctor.','www.photobucket.com/user/ontour/gallery/46776',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (43241,'19-05-17','massa','www.photobucket.com/user/ontour/gallery/43241',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (28628,'25-03-17','lorem,','www.photobucket.com/user/ontour/gallery/28628',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (46239,'20-07-17','ligula. Aliquam erat volutpat.','www.photobucket.com/user/ontour/gallery/46239',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (40712,'24-04-18','Integer tincidunt','www.photobucket.com/user/ontour/gallery/40712',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (13287,'05-12-17','Morbi metus. Vivamus','www.photobucket.com/user/ontour/gallery/13287',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (26930,'28-11-16','dictum eu, eleifend nec, malesuada','www.photobucket.com/user/ontour/gallery/26930',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (6851,'10-05-17','consequat nec,','www.photobucket.com/user/ontour/gallery/6851',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (29083,'21-11-17','augue porttitor interdum.','www.photobucket.com/user/ontour/gallery/29083',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (27592,'23-07-18','amet nulla. Donec non justo.','www.photobucket.com/user/ontour/gallery/27592',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (45798,'28-08-18','nec','www.photobucket.com/user/ontour/gallery/45798',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (6557,'16-09-18','Integer tincidunt','www.photobucket.com/user/ontour/gallery/6557',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (40757,'07-08-18','Vivamus euismod urna. Nullam lobortis','www.photobucket.com/user/ontour/gallery/40757',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (36386,'30-09-17','justo. Proin non massa','www.photobucket.com/user/ontour/gallery/36386',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (31424,'27-12-16','Sed dictum. Proin eget','www.photobucket.com/user/ontour/gallery/31424',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (33824,'08-02-18','vel, venenatis vel, faucibus id,','www.photobucket.com/user/ontour/gallery/33824',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (27728,'20-07-18','fringilla. Donec','www.photobucket.com/user/ontour/gallery/27728',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (6572,'04-08-18','orci. Phasellus dapibus','www.photobucket.com/user/ontour/gallery/6572',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (40847,'11-06-18','cursus purus. Nullam scelerisque','www.photobucket.com/user/ontour/gallery/40847',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (11391,'24-04-18','ac orci. Ut semper','www.photobucket.com/user/ontour/gallery/11391',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (42863,'18-02-17','Cras convallis convallis','www.photobucket.com/user/ontour/gallery/42863',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (17718,'04-07-18','sollicitudin a, malesuada id,','www.photobucket.com/user/ontour/gallery/17718',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (43699,'14-11-16','at, velit.','www.photobucket.com/user/ontour/gallery/43699',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (12520,'30-01-17','sit','www.photobucket.com/user/ontour/gallery/12520',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (28477,'25-10-17','ornare, facilisis eget,','www.photobucket.com/user/ontour/gallery/28477',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (33133,'30-08-17','sodales elit erat','www.photobucket.com/user/ontour/gallery/33133',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (40393,'16-10-17','sem ut dolor dapibus','www.photobucket.com/user/ontour/gallery/40393',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (7306,'02-01-18','dolor vitae dolor.','www.photobucket.com/user/ontour/gallery/7306',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (33272,'21-10-17','mi pede, nonummy ut,','www.photobucket.com/user/ontour/gallery/33272',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (31130,'25-07-18','aliquet. Phasellus fermentum','www.photobucket.com/user/ontour/gallery/31130',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (5905,'31-10-17','parturient','www.photobucket.com/user/ontour/gallery/5905',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (8732,'14-05-18','venenatis','www.photobucket.com/user/ontour/gallery/8732',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (20035,'24-09-17','posuere cubilia','www.photobucket.com/user/ontour/gallery/20035',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (29078,'11-05-17','Suspendisse aliquet, sem ut','www.photobucket.com/user/ontour/gallery/29078',1,1,1,'apo@ontour.cl',1);
INSERT INTO DEPOSITO (MONTO,FECHA,COMENTARIO,URLCAPTURACOMPROBANTE,IDCOLEGIOFK,IDCURSOFK,IDTIPOUSUARIOFK,CORREOFK,IDAPODERADOFK) VALUES (26703,'28-09-18','Donec egestas.','www.photobucket.com/user/ontour/gallery/26703',1,1,1,'apo@ontour.cl',1);
*/

--PAQUETE TURISTICO

INSERT INTO PAQUETETURISTICO (ORIGEN,DESTINO,DIAS,NOCHES,PRECIOPORALUMNO,PROVEEDORTRANSPORTE,PROVEEDORALOJAMIENTO) VALUES ('Metropolitana de Santiago','Puerto Varas',5,4,378408,'Magna Ut PC','Laoreet Ltd');
INSERT INTO PAQUETETURISTICO (ORIGEN,DESTINO,DIAS,NOCHES,PRECIOPORALUMNO,PROVEEDORTRANSPORTE,PROVEEDORALOJAMIENTO) VALUES ('Metropolitana de Santiago','Bariloche',7,6,363616,'Luctus Et Company','Nam Ligula LLP');
INSERT INTO PAQUETETURISTICO (ORIGEN,DESTINO,DIAS,NOCHES,PRECIOPORALUMNO,PROVEEDORTRANSPORTE,PROVEEDORALOJAMIENTO) VALUES ('Metropolitana de Santiago','Pucon',7,6,496441,'Donec Company','Vehicula Et LLP');
INSERT INTO PAQUETETURISTICO (ORIGEN,DESTINO,DIAS,NOCHES,PRECIOPORALUMNO,PROVEEDORTRANSPORTE,PROVEEDORALOJAMIENTO) VALUES ('Metropolitana de Santiago','Valdivia',6,5,244617,'Vulputate Limited','Vivamus Molestie LLP');
INSERT INTO PAQUETETURISTICO (ORIGEN,DESTINO,DIAS,NOCHES,PRECIOPORALUMNO,PROVEEDORTRANSPORTE,PROVEEDORALOJAMIENTO) VALUES ('Metropolitana de Santiago','Isla de Pascua',5,4,454278,'Donec Institute','Molestie Consulting');

--CONTRATO

INSERT INTO CONTRATO (FECHA,COMENTARIO,ISACTIVO,IDCURSOFK,IDEJECUTIVOFK,IDPAQUETETURISTICOFK) VALUES ('15-07-17','Lorem',1,1,1,5);
INSERT INTO CONTRATO (FECHA,COMENTARIO,ISACTIVO,IDCURSOFK,IDEJECUTIVOFK,IDPAQUETETURISTICOFK) VALUES ('20-10-17','Lorem',1,2,1,5);
INSERT INTO CONTRATO (FECHA,COMENTARIO,ISACTIVO,IDCURSOFK,IDEJECUTIVOFK,IDPAQUETETURISTICOFK) VALUES ('25-02-17','Lorem',1,3,2,1);
INSERT INTO CONTRATO (FECHA,COMENTARIO,ISACTIVO,IDCURSOFK,IDEJECUTIVOFK,IDPAQUETETURISTICOFK) VALUES ('16-12-17','Lorem',1,4,2,2);
INSERT INTO CONTRATO (FECHA,COMENTARIO,ISACTIVO,IDCURSOFK,IDEJECUTIVOFK,IDPAQUETETURISTICOFK) VALUES ('11-09-17','Lorem',0,5,3,3);

--ACTIVIDAD
--Fecha agregada
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('nec','200000','17/04/2017',1);
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('lobortis.','120000','25/08/2017',1);
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('arcu','200000','10/09/2017',2);
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('nulla.','200000','10/10/2017',2);
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('ornare,','150000','06/06/2017',3);
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('Vivamus','180000','05/11/2017',3);
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('nascetur','50000','07/08/2017',4);
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('lobortis','100000','05/11/2017',4);
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('Integer','200000','01/09/2017',5);
INSERT INTO ACTIVIDAD (DESCRIPCION,MONTORECAUDADO,FECHA,IDCURSOFK) VALUES ('Duis','80000','21/10/2017',5);