--COSULTAS JOIN

--JOIN ENTRE APODERADO, CONTRATO, PAQUETE TURISTICO
SELECT A.IDAPODERADO, C.IDCONTRATO, C.IDCURSOFK, C.ISACTIVO, P.ORIGEN, P.DESTINO, C.IDPAQUETETURISTICOFK FROM CONTRATO C 
FULL OUTER JOIN APODERADO A ON C.IDCURSOFK = A.IDCURSOFK
FULL OUTER JOIN PAQUETETURISTICO P ON P.IDPAQUETETURISTICO = C.IDPAQUETETURISTICOFK
WHERE A.IDAPODERADO = 1; 

--REVISA SI EL CONTRATO ESTA ACTIVO, SEGUN EL CURSO
SELECT ISACTIVO FROM CONTRATO WHERE IDCURSOFK = 1;

--JOIN ENTRE 3 TABLAS FUNCIONAL
SELECT NVL(A.NOMBRE, E.NOMBRE), U.CORREO, U.CLAVE, U.IDTIPOUSUARIOFK, A.IDAPODERADO
FROM USUARIO U
FULL OUTER JOIN APODERADO A ON U.CORREO = A.CORREOFK
FULL OUTER JOIN EJECUTIVO E ON E.CORREOFK = U.CORREO
ORDER BY U.IDTIPOUSUARIOFK, U.CORREO;

SELECT * FROM USUARIO;
SELECT * FROM APODERADO;
SELECT * FROM EJECUTIVO;

SELECT A.NOMBRE, U.CORREO, U.CLAVE
FROM USUARIO U INNER JOIN APODERADO A ON U.CORREO = A.CORREOFK;

SELECT A.NOMBRE, U.CORREO, U.CLAVE, IDTIPOUSUARIOFK FROM USUARIO U JOIN APODERADO A ON U.CORREO = A.CORREOFK WHERE U.CORREO = 'exe5@ontour.cl' AND U.CLAVE = '9000';

--Para SignUp.aspx
SELECT CU.IDCURSO, CONCAT(CONCAT(CU.GRADOCURSO, ' '),CU.LETRACURSO) AS NOMBRECURSO, CU.IDCOLEGIOFK, CO.NOMBRECOLEGIO FROM CURSO CU JOIN COLEGIO CO
ON CU.IDCOLEGIOFK = CO.IDCOLEGIO
WHERE CO.NOMBRECOLEGIO = 'Instituto Nacional';

SELECT IDCURSO, CONCAT(CONCAT(GRADOCURSO, ' '),LETRACURSO) AS NOMBRECURSO, IDCOLEGIOFK FROM CURSO
WHERE IDCOLEGIOFK = 2;

/*
SELECT COALESCE (A.NOMBRE, E.NOMBRE) AS "NOMBRE DE TODOS", COALESCE(A.CORREOFK, E.CORREOFK), U.CLAVE, U.IDTIPOUSUARIOFK FROM USUARIO U
LEFT OUTER JOIN APODERADO A ON A.CORREOFK = U.CORREO
RIGHT OUTER JOIN EJECUTIVO E ON U.CORREO = E.CORREOFK;
*/

/*
SELECT COALESCE (A.NOMBRE, E.NOMBRE) AS "NOMBRE DE TODOS", COALESCE(A.CORREOFK, E.CORREOFK), U.CLAVE, U.IDTIPOUSUARIOFK FROM APODERADO A 
LEFT JOIN USUARIO U ON A.CORREOFK = U.CORREO
RIGHT JOIN EJECUTIVO E ON E.CORREOFK = A.CORREOFK;
*/